### ISSUE TITLE
Camera is not opening when clicking Start button

### ISSUE THREAD

**Issue by AntonioTannoury** [whitphx/streamlit-webrtc-example#117]
Hello, 
I was just testing the suggested demo app after the new version release and encountered the following behavior:
First, on the start button it starts loading...
![Capture1](https://user-images.githubusercontent.com/97980187/156359154-2415f2be-92aa-435d-b751-60c0decfb520.PNG)

Then, after a while (20sec approx.) it changes to the following screen...
![Capture2](https://user-images.githubusercontent.com/97980187/156359210-7992228c-dc6c-4e8d-a45c-95ce1ab281a9.PNG)

After that the camera does not open and returns to the initial state.

**Comment by whitphx** [comment]
Seems to be the same as https://github.com/whitphx/streamlit-webrtc/issues/44#issuecomment-773314359
https://github.com/whitphx/streamlit-webrtc#network-connectivity may also help.

**Comment by AntonioTannoury** [comment]
> Seems to be the same as [whitphx/streamlit-webrtc#44 (comment)](https://github.com/whitphx/streamlit-webrtc/issues/44#issuecomment-773314359) https://github.com/whitphx/streamlit-webrtc#network-connectivity may also help.

Thanks for the reply, will try the suggested solutions and get back to you
