### ISSUE TITLE
Over resource limits on Streamlit Cloud

### ISSUE THREAD

**Issue by jadler-13** [whitphx/streamlit-webrtc-example#184]
Hey there :wave: Just wanted to let you know that [your app on Streamlit Cloud deployed from this repo](https://webrtc.streamlit.app/whitphx/streamlit-webrtc-example/main/app.py) has gone over its resource limits. Access to the app is temporarily limited. Visit the app to see more details and possible solutions.

**Comment by whitphx** [comment]
Thanks! It's fixed.
