### ISSUE TITLE
Examples do not work

### ISSUE THREAD

**Issue by poloniki** [whitphx/streamlit-webrtc-example#231]
Good day, could you please check if everything is fine with the examples page, nothing seem to work right now. Tried on different browsers and devices.

**Comment by whitphx** [comment]
Thank you for reporting this!

I confirmed it and deployed a [(potential) fix](https://github.com/whitphx/streamlit-webrtc/pull/1375).

Can you please try using the example again now? Thanks!

Ref: https://discuss.streamlit.io/t/webrtc-component-examples-are-not-working-in-streamlit-anymore/50557

**Comment by poloniki** [comment]
Everything works! Thanks a lot =)
