### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by anubhav201241** [whitphx/streamlit-webrtc-example#44]
Hi @whitphx ,The streamlet link that you have provide in about section is not working it is showing error please solve it

**Comment by whitphx** [comment]
I guess this is fundamentally a Sharing's bug and posted a comment: https://discuss.streamlit.io/t/sharing-environment-is-not-consistent/14749

**Comment by whitphx** [comment]
Regardless of that, I found a solution. Fixed.

**Comment by anubhav201241** [comment]
@whitphx Can you provide link of that where your webcam streamlet is working, whenever I'm opening it it is showing error

**Comment by whitphx** [comment]
🤔 
I can use it now: https://share.streamlit.io/whitphx/streamlit-webrtc-example/main/app.py

Which page do you encounter the error?

**Comment by anubhav201241** [comment]
It is taking too much long time to run, and webcam is not opening in it

**Comment by anubhav201241** [comment]
share.streamlit.io/whitphx/streamlit-we talking about this site this site is showing error and the site which you have send in it webcam is opening but not showing

**Comment by whitphx** [comment]
[This post](https://github.com/whitphx/streamlit-webrtc/issues/44#issuecomment-773314359) might help
